# fly.toml app configuration file generated for retreatreg-rest on 2024-10-03T11:45:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'retreatreg-rest'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
